### ISSUE TITLE
But you need to fix the image field so that it is optional and only displayed if available

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [CaddyDz/NovaPreviewResource#1]
Thanks for the wonderful package!
But you need to fix the image field so that it is optional and only displayed if available

https://github.com/CaddyDz/NovaPreviewResource/blob/ff0a37bea7feaee8a10c910bc53542b1bbfec85f/resources/js/components/IndexField.vue#L9

**Comment by CaddyDz** [comment]
Good suggestion, working on it

**Comment by oleksandr-roskovynskyi** [comment]
> Good suggestion, working on it

I have already sent you a pull request

**Comment by oleksandr-roskovynskyi** [comment]
https://github.com/CaddyDz/NovaPreviewResource/pull/2

**Comment by CaddyDz** [comment]
Closed by #2
