### ISSUE TITLE
You are logging options for each resource

### ISSUE THREAD

**Issue by stufarquhar** [CaddyDz/NovaPreviewResource#4]
Great package, I did notice that are you are logging out the options for each loaded resource. Just a FYI.

public function options($options)
	{
		info($options);
		if (is_callable($options)) {
			$options = $options();
		}

		return $this->withMeta([
			'options' => with(collect($options), function ($options) {
				return $options->map(function ($label, $name) use ($options) {
					return $options->isAssoc()
						? ['label' => $label, 'name' => $name]
						: ['label' => $label, 'name' => $label];
				})->values()->all();
			}),
		]);
	}

**Comment by CaddyDz** [comment]
Thank you for noticing and reporting
